version: '2'

services:

  influxdb:
    image: influxdb
    expose:
      - "8083"
      - "8086"
    ports:
      - "8086:8086"
    volumes:
      - ./influx-data:/var/lib/influxdb
    networks:
      - tick

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - tick
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    networks:
      - tick
    depends_on:
      - influxdb

  chronograf:
    image: "quay.io/influxdb/chronograf"
    ports:
      - "8888:8888"
    networks:
      - tick
    depends_on:
      - influxdb

networks:
  tick:
    driver: bridge
